// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using RajMango.DataAccess.Contexts;

#nullable disable

namespace RajMango.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260517000002_RenameExpenseTransactionIdToPaymentReference")]
    partial class RenameExpenseTransactionIdToPaymentReference
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
