// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RajMango.DataAccess.Contexts;

#nullable disable

namespace RajMango.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260519000001_NormalizePhoneNumbers_AddUniqueIndexes")]
    partial class NormalizePhoneNumbers_AddUniqueIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RajMango.Domain.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            CreatedAt = new DateTime(2026, 5, 18, 19, 52, 48, 869, DateTimeKind.Unspecified).AddTicks(3830),
                            CreatedBy = 1,
                            DeletedBy = 0,
                            Email = "systemadmin@rajmango.com",
                            EmailConfirmed = true,
                            FirstName = "System",
                            IsActive = true,
                            IsDeleted = false,
                            IsLocked = false,
                            LastName = "Admin",
                            PasswordHash = "AQAAAAIAAYagAAAAEDE/v9e0mVuBEu6lrnlF/4j9+zEAOk/hYcYGWjbtkXcT3g+m/IXMuAehq/e7fg22EQ==",
                            PhoneNumber = "+8801700000001",
                            PhoneNumberConfirmed = true,
                            UpdatedBy = 0,
                            UserName = "SA1000"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            CreatedAt = new DateTime(2026, 5, 18, 19, 52, 49, 40, DateTimeKind.Unspecified).AddTicks(5328),
                            CreatedBy = 1,
                            DeletedBy = 0,
                            Email = "admin@rajmango.com",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            IsActive = true,
                            IsDeleted = false,
                            IsLocked = false,
                            LastName = "User",
                            PasswordHash = "AQAAAAIAAYagAAAAEB6l+JawdWyWIZi8NF2uC+Amnzxl76IrPFjNoP+XYX/UEgvngFA9xQ5EritkrN91tw==",
                            PhoneNumber = "+8801700000002",
                            PhoneNumberConfirmed = true,
                            UpdatedBy = 0,
                            UserName = "AU2000"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            CreatedAt = new DateTime(2026, 5, 18, 19, 52, 49, 211, DateTimeKind.Unspecified).AddTicks(2766),
                            CreatedBy = 1,
                            DeletedBy = 0,
                            Email = "general@rajmango.com",
                            EmailConfirmed = true,
                            FirstName = "General",
                            IsActive = true,
                            IsDeleted = false,
                            IsLocked = false,
                            LastName = "User",
                            PasswordHash = "AQAAAAIAAYagAAAAEGX8doiEh5x2yHLQxzr7uK867tcQNM+m1lYJz6fmjiV1CufysvzQUCMP+DltPde92A==",
                            PhoneNumber = "+8801700000003",
                            PhoneNumberConfirmed = true,
                            UpdatedBy = 0,
                            UserName = "GU3000"
                        });
                });

#pragma warning restore 612, 618
        }
    }
}
